#!/bin/bash

# Ce script met à jour odoo selon l'état d'avancement du projet sur le
# dépôt officiel odoo sur github


# La ligne suivante détermine si le dépôt local est sur la version 8.0
# ou 9.0 de odoo
branche=$(git branch -r | awk '{FS="/"} /->/ {print $3}')

if [[ -z $branche ]]; then
    branche=8.0
    echo "On est sur la branche $branche"
else
    echo "On est sur la branche $branche"
fi

# On interroge la date du dernier commit disponible sur le dépôt local
date_curr_HEAD=$(git show HEAD --format=%ci | head -1 | sed 's/\+.*//;s/ $//;s/$/Z/;s/ /T/')
echo "Le dernier commit en local remonte au $date_curr_HEAD"

# On interroge github au travers de  son API pour compter le nombre de
# commits que le dépôt local a en retard
number_commits_forward=$(curl -si "https://api.github.com/repos/odoo/odoo/commits?sha=$branche&since=$date_curr_HEAD" |  grep \"commit\"  | wc -l)
echo "Vous avez $number_commits_forward commits de différence avec l'état d'avancement du projet Odoo$branche"

#Si retard on fetch les commits manquants
if [ $number_commits_forward -gt 0 ]; then
    profondeur_local=$(git log --oneline | wc -l)
    git fetch --depth $(($number_commits_forward + $profondeur_local))
else
    echo "There is no new commits"
fi
